# SCSS-Lint Configuration File
# https://github.com/brigade/scss-lint

scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: false
    max_elements: 1

  BorderZero:
    enabled: true
    convention: zero # or `none`

  ChainedClasses:
    enabled: false

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: true
    style: silent

  DebugStatement:
    enabled: true

  # The following DeclarationOrder is used in conjuction with the PropertySortOrder below
  # to place @extend declarations and @include declarations above CSS properties in sort order.
  DeclarationOrder:
    enabled: true

  DisableLinterReason:
    enabled: false

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 4

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  # The following NameFormat set to false to prevent Bourbon, Bitters and
  # Underscores SASS variables from thowing errors due to not following naming
  # conventions.
  NameFormat:
    enabled: false
    allow_leading_underscore: true
    convention: hyphenated_lowercase # or 'camel_case', or 'snake_case', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 3
    ignore_parent_selectors: false

  PlaceholderInExtend:
    enabled: true

  PrivateNamingConvention:
    enabled: false
    prefix: _

  PropertyCount:
    enabled: true
    include_nested: false
    max_properties: 10

  # The following sort order based on CSScomb's default sort order. For more info visit:
  # https://github.com/csscomb/csscomb.js
  PropertySortOrder:
    enabled: true
    order: [
      "position",
      "top",
      "right",
      "bottom",
      "left",
      "z-index",
      "display",
      "visibility",
      "-webkit-flex-direction",
      "-moz-flex-direction",
      "-ms-flex-direction",
      "-o-flex-direction",
      "flex-direction",
      "-webkit-flex-order",
      "-moz-flex-order",
      "-ms-flex-order",
      "-o-flex-order",
      "flex-order",
      "-webkit-flex-pack",
      "-moz-flex-pack",
      "-ms-flex-pack",
      "-o-flex-pack",
      "flex-pack",
      "float",
      "clear",
      "-webkit-flex-align",
      "-moz-flex-align",
      "-ms-flex-align",
      "-o-flex-align",
      "flex-align",
      "overflow",
      "-ms-overflow-x",
      "-ms-overflow-y",
      "overflow-x",
      "overflow-y",
      "-webkit-overflow-scrolling",
      "clip",
      "-webkit-box-sizing",
      "-moz-box-sizing",
      "box-sizing",
      "margin",
      "margin-top",
      "margin-right",
      "margin-bottom",
      "margin-left",
      "padding",
      "padding-top",
      "padding-right",
      "padding-bottom",
      "padding-left",
      "min-width",
      "min-height",
      "max-width",
      "max-height",
      "width",
      "height",
      "outline",
      "outline-width",
      "outline-style",
      "outline-color",
      "outline-offset",
      "border",
      "border-spacing",
      "border-collapse",
      "border-width",
      "border-style",
      "border-color",
      "border-top",
      "border-top-width",
      "border-top-style",
      "border-top-color",
      "border-right",
      "border-right-width",
      "border-right-style",
      "border-right-color",
      "border-bottom",
      "border-bottom-width",
      "border-bottom-style",
      "border-bottom-color",
      "border-left",
      "border-left-width",
      "border-left-style",
      "border-left-color",
      "-webkit-border-radius",
      "-moz-border-radius",
      "border-radius",
      "-webkit-border-top-left-radius",
      "-moz-border-radius-topleft",
      "border-top-left-radius",
      "-webkit-border-top-right-radius",
      "-moz-border-radius-topright",
      "border-top-right-radius",
      "-webkit-border-bottom-right-radius",
      "-moz-border-radius-bottomright",
      "border-bottom-right-radius",
      "-webkit-border-bottom-left-radius",
      "-moz-border-radius-bottomleft",
      "border-bottom-left-radius",
      "-webkit-border-image",
      "-moz-border-image",
      "-o-border-image",
      "border-image",
      "-webkit-border-image-source",
      "-moz-border-image-source",
      "-o-border-image-source",
      "border-image-source",
      "-webkit-border-image-slice",
      "-moz-border-image-slice",
      "-o-border-image-slice",
      "border-image-slice",
      "-webkit-border-image-width",
      "-moz-border-image-width",
      "-o-border-image-width",
      "border-image-width",
      "-webkit-border-image-outset",
      "-moz-border-image-outset",
      "-o-border-image-outset",
      "border-image-outset",
      "-webkit-border-image-repeat",
      "-moz-border-image-repeat",
      "-o-border-image-repeat",
      "border-image-repeat",
      "-webkit-border-top-image",
      "-moz-border-top-image",
      "-o-border-top-image",
      "border-top-image",
      "-webkit-border-right-image",
      "-moz-border-right-image",
      "-o-border-right-image",
      "border-right-image",
      "-webkit-border-bottom-image",
      "-moz-border-bottom-image",
      "-o-border-bottom-image",
      "border-bottom-image",
      "-webkit-border-left-image",
      "-moz-border-left-image",
      "-o-border-left-image",
      "border-left-image",
      "-webkit-border-corner-image",
      "-moz-border-corner-image",
      "-o-border-corner-image",
      "border-corner-image",
      "-webkit-border-top-left-image",
      "-moz-border-top-left-image",
      "-o-border-top-left-image",
      "border-top-left-image",
      "-webkit-border-top-right-image",
      "-moz-border-top-right-image",
      "-o-border-top-right-image",
      "border-top-right-image",
      "-webkit-border-bottom-right-image",
      "-moz-border-bottom-right-image",
      "-o-border-bottom-right-image",
      "border-bottom-right-image",
      "-webkit-border-bottom-left-image",
      "-moz-border-bottom-left-image",
      "-o-border-bottom-left-image",
      "border-bottom-left-image",
      "background",
      "filter:progid:DXImageTransform.Microsoft.AlphaImageLoader",
      "background-color",
      "background-image",
      "background-attachment",
      "background-position",
      "-ms-background-position-x",
      "-ms-background-position-y",
      "background-position-x",
      "background-position-y",
      "-webkit-background-clip",
      "-moz-background-clip",
      "background-clip",
      "background-origin",
      "-webkit-background-size",
      "-moz-background-size",
      "-o-background-size",
      "background-size",
      "background-repeat",
      "box-decoration-break",
      "-webkit-box-shadow",
      "-moz-box-shadow",
      "box-shadow",
      "color",
      "table-layout",
      "caption-side",
      "empty-cells",
      "list-style",
      "list-style-position",
      "list-style-type",
      "list-style-image",
      "quotes",
      "content",
      "counter-increment",
      "counter-reset",
      "-ms-writing-mode",
      "vertical-align",
      "text-align",
      "-webkit-text-align-last",
      "-moz-text-align-last",
      "-ms-text-align-last",
      "text-align-last",
      "text-decoration",
      "text-emphasis",
      "text-emphasis-position",
      "text-emphasis-style",
      "text-emphasis-color",
      "text-indent",
      "-ms-text-justify",
      "text-justify",
      "text-outline",
      "text-transform",
      "text-wrap",
      "-ms-text-overflow",
      "text-overflow",
      "text-overflow-ellipsis",
      "text-overflow-mode",
      "text-shadow",
      "white-space",
      "word-spacing",
      "-ms-word-wrap",
      "word-wrap",
      "-ms-word-break",
      "word-break",
      "-moz-tab-size",
      "-o-tab-size",
      "tab-size",
      "-webkit-hyphens",
      "-moz-hyphens",
      "hyphens",
      "letter-spacing",
      "font",
      "font-weight",
      "font-style",
      "font-variant",
      "font-size-adjust",
      "font-stretch",
      "font-size",
      "font-family",
      "src",
      "line-height",
      "opacity",
      "-ms-filter:\\'progid:DXImageTransform.Microsoft.Alpha",
      "filter:progid:DXImageTransform.Microsoft.Alpha(Opacity",
      "-ms-interpolation-mode",
      "-webkit-filter",
      "-ms-filter",
      "filter",
      "resize",
      "cursor",
      "nav-index",
      "nav-up",
      "nav-right",
      "nav-down",
      "nav-left",
      "-webkit-transition",
      "-moz-transition",
      "-ms-transition",
      "-o-transition",
      "transition",
      "-webkit-transition-delay",
      "-moz-transition-delay",
      "-ms-transition-delay",
      "-o-transition-delay",
      "transition-delay",
      "-webkit-transition-timing-function",
      "-moz-transition-timing-function",
      "-ms-transition-timing-function",
      "-o-transition-timing-function",
      "transition-timing-function",
      "-webkit-transition-duration",
      "-moz-transition-duration",
      "-ms-transition-duration",
      "-o-transition-duration",
      "transition-duration",
      "-webkit-transition-property",
      "-moz-transition-property",
      "-ms-transition-property",
      "-o-transition-property",
      "transition-property",
      "-webkit-transform",
      "-moz-transform",
      "-ms-transform",
      "-o-transform",
      "transform",
      "-webkit-transform-origin",
      "-moz-transform-origin",
      "-ms-transform-origin",
      "-o-transform-origin",
      "transform-origin",
      "-webkit-animation",
      "-moz-animation",
      "-ms-animation",
      "-o-animation",
      "animation",
      "-webkit-animation-name",
      "-moz-animation-name",
      "-ms-animation-name",
      "-o-animation-name",
      "animation-name",
      "-webkit-animation-duration",
      "-moz-animation-duration",
      "-ms-animation-duration",
      "-o-animation-duration",
      "animation-duration",
      "-webkit-animation-play-state",
      "-moz-animation-play-state",
      "-ms-animation-play-state",
      "-o-animation-play-state",
      "animation-play-state",
      "-webkit-animation-timing-function",
      "-moz-animation-timing-function",
      "-ms-animation-timing-function",
      "-o-animation-timing-function",
      "animation-timing-function",
      "-webkit-animation-delay",
      "-moz-animation-delay",
      "-ms-animation-delay",
      "-o-animation-delay",
      "animation-delay",
      "-webkit-animation-iteration-count",
      "-moz-animation-iteration-count",
      "-ms-animation-iteration-count",
      "-o-animation-iteration-count",
      "animation-iteration-count",
      "-webkit-animation-direction",
      "-moz-animation-direction",
      "-ms-animation-direction",
      "-o-animation-direction",
      "animation-direction",
      "pointer-events",
      "unicode-bidi",
      "direction",
      "-webkit-columns",
      "-moz-columns",
      "columns",
      "-webkit-column-span",
      "-moz-column-span",
      "column-span",
      "-webkit-column-width",
      "-moz-column-width",
      "column-width",
      "-webkit-column-count",
      "-moz-column-count",
      "column-count",
      "-webkit-column-fill",
      "-moz-column-fill",
      "column-fill",
      "-webkit-column-gap",
      "-moz-column-gap",
      "column-gap",
      "-webkit-column-rule",
      "-moz-column-rule",
      "column-rule",
      "-webkit-column-rule-width",
      "-moz-column-rule-width",
      "column-rule-width",
      "-webkit-column-rule-style",
      "-moz-column-rule-style",
      "column-rule-style",
      "-webkit-column-rule-color",
      "-moz-column-rule-color",
      "column-rule-color",
      "break-before",
      "break-inside",
      "break-after",
      "page-break-before",
      "page-break-inside",
      "page-break-after",
      "orphans",
      "widows",
      "-ms-zoom",
      "zoom",
      "max-zoom",
      "min-zoom",
      "user-zoom",
      "orientation"
      ]
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false

  PropertySpelling:
    enabled: true
    extra_properties: []
    disabled_properties: []

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties: {}

  PseudoElement:
    enabled: true

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase # or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3, 4]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space'

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableColon:
    enabled: true
    style: one_space # or 'no_space', 'at_least_one_space' or 'one_space_or_newline'

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true
    style: one_space # or 'at_least_one_space', or 'no_space'

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: double_quotes # or double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: true

  TransitionAll:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: true
    properties: []

  VendorPrefix:
    enabled: true
    identifier_list: bourbon
    additional_identifiers: []
    excluded_identifiers: []

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
